### ISSUE TITLE
2.7.1 checklist

### ISSUE THREAD

**Issue by aquette** [networkupstools/nut#37]
Checklist for the 2.7.1 interim release:
- [x] @clepple: update dowload info for git
- [x] update client info with walNUT
- [x] address issue #30 (NSS support broke upsc output)
- [x] address issue #15 (Avoid "2.6.x-Unversioned Directory" version numbers)
- [x] check branch bcmxcp and merge if ok
- [x] check branch voltronic-driver and merge if ok (but see #57)
- [x] #57: check branch blzr and merge if ok; possibly removing voltronic
- [x] add Tripp Lite information to drivers.list
- [x] check branch powercom-instant-commands and merge if ok
- [x] update news/upgrading files
